### PR TITLE
Role generation complete

### PR DESCRIPTION
**Pull request by camdenorrb**
I didn't test any of this, but it should work.... lol

### CODE REVIEW

**Comment by AKrotchko** [comment]
I read through everything and it looks good, I'm going to run some brief testing to ensure everything works as expected.

**Comment by camdenorrb** [comment]
Ok

**Comment by AKrotchko** [comment]
Bot is not assigning or creating any roles when I ran tests. All I see is the bot printing the name of the rich presence with our delimiter in the testing channel. Nothing in the log, either.

**Comment by camdenorrb** [comment]
Rather than closing, ask for changes. Also I don’t think you tested properly

**Comment by AKrotchko** [comment]
Everything looks good, no major issues I see. Tests look good, too.

**Pull request merged**
